// packages/vue/ZikoUI.vue
<template>
    <ziko-ui ref="containerRef" data-engine="ziko"></ziko-ui>
  </template>
  <script>
  import {ZikoUIElement} from "ziko"
  export default {
    props: {
      ui: Object
    },
    mounted() {
      if (this.$refs.containerRef && this.ui instanceof ZikoUIElement) {
        this.$refs.containerRef.innerHTML = "";
        this.$refs.containerRef.appendChild(this.ui.element);
      }
    }
  };
  </script>

// packages/svelte/ZikoUI.svelte
<div bind:this={containerRef} data-engine="ziko"></div>

<script>
  let containerRef;

  import { onMount } from 'svelte';

  onMount(() => {
    if (containerRef && ui instanceof ZikoUIElement) {
      containerRef.innerHTML = "";
      containerRef.appendChild(ui.element);
    }
  });
  export let ui;
</script>
