// solid/solid-wrapper.js
import {ZikoUIElement} from "ziko"
import { render } from 'solid-js/web'
import { createComponent } from 'solid-js'
function SolidWrapper(Component, props){
    let ui=new ZikoUIElement("div").setAttr({
        dataWrapper : "solid-js"
    }).style({
        display : "contents"
    })
    render(() => createComponent(Component,props), ui.element);
    Object.defineProperty(ui, 'element', {
        get() {
          return this.__ele__.firstChild;
        },
        configurable: false,
      });
    return ui
}

export{
    SolidWrapper
}

// react/react-wrapper.jsx
import ReactDOM from "react-dom/client";
import { ZikoUIElement} from "ziko"
export const ReactWrapper = (Component) => {
    const container = document.createElement("div");
    const root = ReactDOM.createRoot(container);
    root.render(Component);
    const ui = new ZikoUIElement(container).style({
        display : "contents"
    }).setAttr({
        dataWrapper : "react"
    });
    Object.defineProperty(ui, 'element', {
        get() {
          return this._element.firstChild;
        },
        configurable: false,
      });
    return ui;
};
