// wrappers/solid/solid-wrapper.js
import {UIElement} from "ziko"
import { render } from 'solid-js/web'
import { createComponent } from 'solid-js'
function SolidWrapper(Component, props){
    let ui=new UIElement("div").setAttr({
        dataWrapper : "solid-js"
    }).style({
        display : "contents"
    })
    render(() => createComponent(Component,props), ui.element);
    Object.defineProperty(ui, 'element', {
        get() {
          return this.__ele__.firstChild;
        },
        configurable: false,
      });
    return ui
}

export{
    SolidWrapper
}

// wrappers/react/react-wrapper.js
import {createRoot} from "react-dom/client";
import { isValidElement,createElement } from "react";
import { ZikoUIElement} from "ziko"

export const ReactWrapper = (Component, props = {}) => {
    const container = document.createElement("div");
    const root = createRoot(container);
    const isJsx = isValidElement(Component);
    root.render(isJsx ? Component : createElement(Component, props));
    const ui = new ZikoUIElement(container).style({
        display : "contents"
    }).setAttr({
        dataWrapper : "react"
    });
    Object.defineProperty(ui, 'element', {
        get() {
          return this.__ele__.firstChild;
        },
        configurable: false,
      });
    return ui;
};
