// wrappers/dom/vue/dom-wrapper.vue
<template>
    <div 
      ref="containerRef" 
      data-wrapper="ziko-wrapper"
      style="display: contents;"
    ></div>
</template>
<script>
  export default {
    props: {
      ui: Function
    },
    mounted() {
      if (this.$refs.containerRef && this.ui) {
        this.$refs.containerRef.innerHTML = "";
        this.$refs.containerRef.appendChild(this.ui());
      }
    }
  };
</script>

// dom/svelte/dom-wrapper.svelte
<div 
  bind:this={containerRef} 
  data-wrapper="ziko-wrapper"
  style="display: contents;"
></div>

<script>
  import { onMount } from 'svelte';
  export let ui; 
  
  let containerRef;
  onMount(() => {
    if (containerRef && ui instanceof HTMLElement) {
      containerRef.innerHTML = "";  
      containerRef.appendChild(ui); 
    } else {
      console.warn("UI element is not an instance of HTMLElement.");
    }
  });
</script>
