// dom/react/dom-wrapper.jsx
import { useRef, useEffect } from 'react';
export function DomWrapper({ children }) {
  const containerRef = useRef(null);
  useEffect(() => {
    if (containerRef.current && children) {
      containerRef.current.innerHTML = '';
      if (!(children instanceof Array)) children = [children];
      children.forEach(child => {
        if (typeof child.type === 'function') {
          const childElement = child.type(child.props);
          if (childElement instanceof HTMLElement) {
            containerRef.current.appendChild(childElement);
          }
        }
      });
    }
  }, [children]);
  return <div 
    data-wrapper="ziko-wrapper" 
    ref={containerRef}
    style={{display : "contents"}}
    ></div>;
}

// wrappers/dom/vue/__dom-wrapper.vue
<template>
    <div 
      ref="containerRef" 
      :data-wrapper="wrapper"
      :data-engine="engine"
      style="display: contents;"
    >
    </div>
</template>
<script>
  export default {
    props: {
      ui: {
        type: [Function, Array],
        required: true,         
        default: null          
      },
      wrapper: {
        type: String,
        required: true,
        default: 'ziko-wrapper'
      },
      engine: {
        type: String,
        required: true,
        default: 'ziko.js'
      }
    },
    mounted() {
    const Wrapper = this.$refs.containerRef
    if (Wrapper) {
      Wrapper.innerHTML = "";
      if(this.ui instanceof HTMLElement) Wrapper.appendChild(this.ui);
      else if(this.ui instanceof Array) this.ui.forEach(item=> Wrapper.appendChild(item))
    }
  }
  };
</script>
