// vue/ziko-wrapper.vue
<template>
  <div 
    ref="containerRef" 
    data-wrapper="ziko-wrapper"
    data-engine="ziko.js"
    style="display: contents;"
  ></div>
</template>
<script>
import {ZikoUIElement} from "ziko"
export default {
  props: {
    // ui: Object
    ui : Function
  },
  mounted() {
    __Ziko__.__Config__.setDefault({render:false})
    if (this.$refs.containerRef && this.ui instanceof ZikoUIElement) {
      this.$refs.containerRef.innerHTML = "";
      // this.$refs.containerRef.appendChild(this.ui.clone().element);
      this.$refs.containerRef.appendChild(this.ui().element);
    }
  }
};
</script>

// svelte/ziko-wrapper.svelte
<div 
  bind:this={containerRef} 
  data-wrapper="ziko-wrapper"
  data-engine="ziko.js"
  style="display: contents;"
></div>
<script>
  import { onMount } from 'svelte';
  import {ZikoUIElement} from "ziko";
  let containerRef;
  __Ziko__.__Config__.setDefault({render:false})
  onMount(() => {
    if (containerRef && ui instanceof ZikoUIElement) {
      containerRef.innerHTML = "";
      containerRef.appendChild(ui.element);
    }
  });
  export let ui;
</script>
