// wrappers/svelte/ziko-wrapper.svelte
<script>
  import { onMount } from 'svelte';
  import { ZikoUIElement } from 'ziko';

  let containerRef;
  export let ui;
  
  __Ziko__.__Config__.setDefault({ render: false });

  onMount(() => {
    if (containerRef && ui) {
      containerRef.innerHTML = "";
      if (ui instanceof ZikoUIElement) containerRef.appendChild(ui.element);
      else if (Array.isArray(ui)) ui.forEach(item => containerRef.appendChild(item.element));
      else console.warn("UI element is not an instance of ZikoUIElement.");
    }
  });
</script>

<div 
  bind:this={containerRef} 
  data-wrapper= "ziko-wrapper" 
  data-engine= "ziko.js"
  style="display: contents;"
></div>

// wrappers/vue/ziko-wrapper.vue
<template>
  <div 
    ref="containerRef" 
    data-wrapper="ziko-wrapper"
    data-engine="ziko.js"
    style="display: contents;"
  ></div>
</template>
<script>
import {ZikoUIElement} from "ziko"
export default {
  props: {
    ui: {
      type: [Function, Array],
      required: true,         
      default: null          
    }
    // ui : Function | [Function]
  },
  mounted() {
    __Ziko__.__Config__.setDefault({render:false})
    const Wrapper = this.$refs.containerRef
    if (Wrapper) {
      Wrapper.innerHTML = "";
      if(this.ui instanceof ZikoUIElement) Wrapper.appendChild(this.ui.element);
      else if(this.ui instanceof Array) this.ui.forEach(item=> Wrapper.appendChild(item.element))
    }
  }
};
</script>
