// wrappers/dom/vue/__dom-wrapper.vue
<template>
    <div 
      ref="containerRef" 
      :data-wrapper="wrapper"
      :data-engine="engine"
      style="display: contents;"
    >
    </div>
</template>
<script>
  export default {
    props: {
      ui: {
        type: [Function, Array],
        required: true,         
        default: null          
      },
      wrapper: {
        type: String,
        required: true,
        default: 'ziko-wrapper'
      },
      engine: {
        type: String,
        required: true,
        default: 'ziko.js'
      }
    },
    mounted() {
    const Wrapper = this.$refs.containerRef
    if (Wrapper) {
      Wrapper.innerHTML = "";
      if(this.ui instanceof HTMLElement) Wrapper.appendChild(this.ui);
      else if(this.ui instanceof Array) this.ui.forEach(item=> Wrapper.appendChild(item))
    }
  }
  };
</script>

// wrappers/svelte/dom-wrapper.svelte
<script>
    import { onMount } from 'svelte';
    export let ui; 
    export let wrapper = null;
    export let engine = null;
    
    let containerRef;
    $: Attributes = {
        ...(wrapper && { 'data-wrapper': wrapper }),
        ...(engine && { 'data-engine': engine })
    };
    onMount(() => {
      if(containerRef){
        containerRef.innerHTML = "";  
        if(ui instanceof HTMLElement){
          containerRef.appendChild(ui); 
        }
        else if(ui instanceof Array){
          ui.forEach(item => containerRef.appendChild(item));
        }
        else console.warn("UI element is not an instance of HTMLElement.");
      }
    });
  </script>
  
  <div 
    bind:this={containerRef} 
    data-wrapper={wrapper}
    data-engine={engine}
    {...Attributes}
    style="display: contents;"
  ></div>

  <!-- <div 
    bind:this={containerRef} 
    data-wrapper={wrapper}
    data-engine={engine}
    style="display: contents;"
  ></div> -->
