// demos/ziko-in-svelte/src/App.svelte
<script >
  import { tags } from "ziko"
  const { h1 } = tags;
  import { ZikoWrapper } from "ziko-wrapper/svelte"
  const Heading = ({msg}) => h1(msg)
</script>

<ZikoWrapper ui={[
  Heading({msg : "Hello from zikojs"}),
  Heading({msg : "Bye "})
  ]} 
/>

<ZikoWrapper ui={Heading({msg : "Other"})}/>

// demos/react-ziko/src/App.jsx
import {h1, p} from "ziko"
import { ZikoWrapper } from "ziko-wrapper/react"

const Heading = ({msg}) => h1(msg)

const Ex = ({color}, ...children) => {
  return p(children[0]).style({color})
}

const App = () =>{
  return(
    <ZikoWrapper>
      <Ex color="red">
          <Heading msg="hello world"/>
          <Heading msg="hello world"/>
      </Ex>
    </ZikoWrapper>
  )
}

export default App
