// svelte/ZikoWrapper.svelte
<section bind:this={containerRef} data-engine="ziko"></section>

<script>
  import { onMount } from 'svelte';
  import {ZikoUIElement} from "ziko";
  let containerRef;
  __Ziko__.__Config__.setDefault({render:false})
  onMount(() => {
    if (containerRef && ui instanceof ZikoUIElement) {
      containerRef.innerHTML = "";
      containerRef.appendChild(ui.element);
    }
  });
  export let ui;
</script>

// vue/ZikoWrapper.vue
<template>
  <section ref="containerRef" data-engine="ziko.js" data-wrapper="ziko-wrapper"></section>
</template>
<script>
import {ZikoUIElement} from "ziko"
export default {
  props: {
    // ui: Object
    ui : Function
  },
  mounted() {
    __Ziko__.__Config__.setDefault({render:false})
    if (this.$refs.containerRef && this.ui instanceof ZikoUIElement) {
      this.$refs.containerRef.innerHTML = "";
      // this.$refs.containerRef.appendChild(this.ui.clone().element);
      this.$refs.containerRef.appendChild(this.ui().element);
    }
  }
};
</script>
