// svelte/examples/basic/src/ZikoUI.svelte
<script>
    import { onMount } from "svelte";
    import { ZikoUIElement } from "ziko";
    let containerRef;
  
    onMount(() => {
      //globalThis.__ZikoConfig__.setDefault({ render: false });
      if (containerRef && ui instanceof ZikoUIElement) {
        containerRef.innerHTML = "";
        containerRef.appendChild(ui.element);
      }
    });
    export let ui;
    // export let x;
  </script>
  
  <div bind:this={containerRef} data-engine="ziko" />

// vue/ZikoUI.vue
<template>
    <ziko-ui ref="containerRef" data-engine="ziko"></ziko-ui>
  </template>
  <script>
  import {ZikoUIElement} from "ziko";
  __ZikoConfig__.setDefault({render:false})
  export default {
    props: {
      ui: Object
    },
    mounted() {
      if (this.$refs.containerRef && this.ui instanceof ZikoUIElement) {
        this.$refs.containerRef.innerHTML = "";
        this.$refs.containerRef.appendChild(this.ui.element);
      }
    }
  };
  </script>
